package com.github.alantr7.codebots.cbslang.high.compiler;

import com.github.alantr7.bytils.buffer.ByteArrayWriter;
import com.github.alantr7.codebots.cbslang.exceptions.ParserException;
import com.github.alantr7.codebots.cbslang.high.parser.Parser;
import com.github.alantr7.codebots.cbslang.high.parser.ast.AST;
import com.github.alantr7.codebots.cbslang.high.parser.ast.expressions.*;
import com.github.alantr7.codebots.cbslang.high.parser.ast.objects.Function;
import com.github.alantr7.codebots.cbslang.high.parser.ast.objects.FunctionSignature;
import com.github.alantr7.codebots.cbslang.high.parser.ast.objects.Primitive;
import com.github.alantr7.codebots.cbslang.high.parser.ast.objects.Scope;
import com.github.alantr7.codebots.cbslang.high.parser.ast.statements.*;
import com.github.alantr7.codebots.cbslang.low.runtime.Program;
import com.github.alantr7.codebots.cbslang.low.runtime.ProgramExecutor;
import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

public class ByteCodeCompiler extends Compiler<byte[]> {

    private final CompilerContext context = new CompilerContext();

    private final ByteArrayWriter builder = new ByteArrayWriter();

    private int autogenerated_labelId = 0;

    public static final byte DEFC           = 1;
    public static final byte IMPF           = 2;
    public static final byte MOV            = 3;
    public static final byte DEFF           = 4;
    public static final byte PUSH           = 5;
    public static final byte POP            = 6;

    public static final byte DEFC_INT       = 1;
    public static final byte DEFC_FLT       = 2;
    public static final byte DEFC_STR       = 3;

    public static final byte ACC_DIR        = 1; // direct access; push ebp
    public static final byte ACC_MEM        = 2; // memory access; push [ebp]
    public static final byte ACC_MEM_OFF    = 2; // memory access with offset; push [ebp +- 3]

    public static final byte REF_REG        = 1;
    public static final byte REF_MEM        = 2;
    public static final byte REF_LIT        = 3; // literal

    public static final byte REG_EBP        = 1;
    public static final byte REG_EIP        = 2;
    public static final byte REG_ESP        = 3;
    public static final byte REG_EAX        = 4;
    public static final byte REG_EBX        = 5;
    public static final byte REG_CMP        = 6;
    public static final byte REG_RAX        = 7;

    public ByteCodeCompiler(AST ast) {
        super(ast);
    }

    @Getter
    private final Scope globalScope = new Scope();

    @Override
    public void compile() {
        ast.constants.forEach((val) -> {
            if (val.type == Primitive.INT)
                compileConstant(DEFC_INT, val.value);
            else if (val.type == Primitive.FLOAT)
                compileConstant(DEFC_FLT, val.value);
            else if (val.type == Primitive.STRING)
                compileConstant(DEFC_STR, val.value);
        });
        compileSignatures();

        // compile main first
        List<Function> functions = new ArrayList<>(ast.functions.values());
        for (int i = 0; i < functions.size(); i++) {
            Function function = functions.get(i);
            if (function.signature.name.equals("main") && function.signature.module == null) {
                functions.set(i, functions.get(0));
                functions.set(0, function);
                break;
            }
        }
        functions.forEach(this::compileFunction);
    }

    public void compileConstant(byte type, Object value) {
        builder.writeU1(DEFC);
        builder.writeU1(type);
        switch (type) {
            case DEFC_INT -> builder.writeInt((int) value);
            case DEFC_FLT -> builder.writeFloat((float) value);
            case DEFC_STR -> builder.writeString((String) value);
        }
    }

    public void compileSignatures() {
        for (FunctionSignature signature : ast.signatures) {
            if (signature.module != null) {
                builder.writeU1(IMPF);
                builder.writeShortString(signature.module);
                builder.writeShortString(signature.name);
            }
        }
    }

    public void compileFunction(Function function) {
        builder.writeU1(DEFF);
        builder.writeShortString(function.signature.name);

        context.currentFunction = function;

        if (!function.signature.name.equals("main")) {
            // builder.append("push ebp\n"); done
            builder.writeU1(PUSH);
            builder.writeU1(ACC_DIR);
            builder.writeU1(REF_REG);
            builder.writeU1(REG_EBP);

            // builder.append("mov ebp, esp\n"); done
            builder.writeU1(MOV);
            builder.writeU1(ACC_DIR);
            builder.writeU1(REF_REG);
            builder.writeU1(REG_ESP);

//            builder.append("sub ebp, 1\n"); todo
        } else {
            // without this it breaks when using constants
            // builder.append("push ebp\n"); done
            builder.writeU1(PUSH);
            builder.writeU1(ACC_DIR);
            builder.writeU1(REF_REG);
            builder.writeU1(REG_EBP);

            // builder.append("mov ebp, esp\n"); done
            builder.writeU1(MOV);
            builder.writeU1(ACC_DIR);
            builder.writeU1(REF_REG);
            builder.writeU1(REG_EBP);
            builder.writeU1(ACC_DIR);
            builder.writeU1(REF_REG);
            builder.writeU1(REG_ESP);

//            builder.append("sub ebp, 1\n"); todo
        }

        for (Statement stmt : function.body) {
            compileStatement(stmt);
        }

        context.currentFunction = null;
    }

    private void compileIf(If ifs, int resultId, boolean isMain) {
        int labelId = autogenerated_labelId++;

        // Compile the chain.
        if (ifs.expression != null) {
            compileExpression(ifs.expression);
//            builder.append("pop eax\n"); todo
//            builder.append("cmp eax, 0\n");
//            builder.append("je if_after_body").append(labelId).append("\n");
        }

        // Body
        for (Statement stmt : ifs.body) {
            compileStatement(stmt);
        }
//        builder.append("sub esp, ").append(ifs.scope.getMemoryUse()).append("\n"); // this was after "if_after_body"
//        builder.append("jmp if_after").append(resultId).append("\n");
//
//        builder.append("if_after_body").append(labelId).append(":\n"); todo

        // Elses
        if (ifs.elseStmt != null) {
            compileIf(ifs.elseStmt, resultId, false);
        }

        // Label after the if statements chain
        if (isMain) {
//            builder.append("if_after").append(resultId).append(":\n"); todo
        }
    }

    private void compileWhile(While loop) {
        int labelId = autogenerated_labelId++;

//        builder.append("loop_start").append(labelId).append(":\n"); todo

        // Compile loop condition.
        compileExpression(loop.expression);
//        builder.append("pop eax\n"); todo
//        builder.append("cmp eax, 0\n");
//        builder.append("je loop_after").append(labelId).append("\n");

        context.loopStack.push(new LoopContext("loop_start" + labelId, "loop_after" + labelId));

        // Body
        for (Statement stmt : loop.body) {
            compileStatement(stmt);
        }

        context.loopStack.pop();

//        builder.append("sub esp, ").append(loop.scope.getMemoryUse()).append("\n");
//        append("halt");
//        builder.append("jmp loop_start").append(labelId).append("\n"); todo

        // Label after the loop
//        builder.append("loop_after").append(labelId).append(":\n"); todo
    }

    private void compileDoWhile(While loop) {
        int labelId = autogenerated_labelId++;
//        builder.append("loop_start").append(labelId).append(":\n"); todo

        // Compile loop condition.
        compileExpression(loop.expression);
//        builder.append("pop eax\n");
//        builder.append("cmp eax, 0\n");
//        builder.append("je loop_after").append(labelId).append("\n"); todo

        context.loopStack.push(new LoopContext("loop_start" + labelId, "loop_after" + labelId));

        // Body
        for (Statement stmt : loop.body) {
            compileStatement(stmt);
        }

        context.loopStack.pop();

//        builder.append("sub esp, ").append(loop.scope.getMemoryUse()).append("\n");
//        append("halt");
//        builder.append("jmp loop_start").append(labelId).append("\n");
//
//        // Label after the loop
//        builder.append("loop_after").append(labelId).append(":\n"); todo
    }

    private void compileFor(For loop) {
        int labelId = autogenerated_labelId++;

        boolean isInitDeclare = false;
        if (loop.init != null) {
            if (loop.init instanceof Operand expr) {
                compileExpression(expr);
//                append("pop"); todo
            } else if (loop.init instanceof Declare declare) {
                compileVariableDeclare(declare);
                isInitDeclare = true;
            }
        }

//        builder.append("loop_start").append(labelId).append(":\n"); todo

        // Compile loop condition.
        compileExpression(loop.condition);
//        builder.append("pop eax\n");
//        builder.append("cmp eax, 0\n");
//        builder.append("je loop_after").append(labelId).append("\n"); todo

        context.loopStack.push(new LoopContext("loop_update" + labelId, "loop_after" + labelId));

        // Body
        for (Statement stmt : loop.body) {
            compileStatement(stmt);
        }

        context.loopStack.pop();

        // Remove local variables from memory
//        builder.append("sub esp, ").append(loop.scope.getMemoryUse()).append("\n"); todo

        // Update
//        builder.append("loop_update").append(labelId).append(":\n"); todo
        if (loop.update != null) {
            compileExpression(loop.update);
//            append("pop"); todo
        }

//        append("halt"); todo

//        builder.append("jmp loop_start").append(labelId).append("\n");
//
//        // Label after the loop
//        builder.append("loop_after").append(labelId).append(":\n");
//        if (isInitDeclare) {
//            builder.append("sub esp, 1\n");
//        } todo
    }

    public void compileStatement(Statement statement) {
        if (statement instanceof Call call) {
            compileExpression(call);
//            append("pop");
//            append("halt"); todo
        }

        else if (statement instanceof While loop) {
            if (loop.isDoWhile) {
                compileDoWhile(loop);
            } else {
                compileWhile(loop);
            }
        }

        else if (statement instanceof If ifs) {
            compileIf(ifs, autogenerated_labelId, true);
        }

        else if (statement instanceof Declare declare) {
            compileVariableDeclare(declare);
        }

        else if (statement instanceof Assign assign) {
            compileExpression(assign);
//            append("pop"); todo
        }

        else if (statement instanceof For loop) {
            compileFor(loop);
        }

        else if (statement instanceof LoopCmd cmd) {
//            append("; Continue/break " + cmd.type);
//            append("sub esp, " + cmd.variableCount);
//            if (cmd.type == LoopCmd.BREAK) {
//                append("jmp " + context.loopStack.peek().exitId);
//            } else if (cmd.type == LoopCmd.CONTINUE) {
//                append("jmp " + context.loopStack.peek().nextIterationId);
//            } todo
        }

        else if (statement instanceof Operand expression) {
            compileExpression(expression);
//            append("pop");
//            append("halt"); todo
        }

        else if (statement instanceof Ret ret) {
            compileExpression(ret.value);
//            builder.append("pop rax\n");
//
//            if (context.currentFunction.signature.name.equals("main")) {
//                builder.append("exit\n");
//            } else {
//                builder.append("ret\n");
//            } todo
        }
    }

    public void compileExpression(Operand operand) {
        if (operand instanceof Literal literal) {
            if (literal.type == Literal.INT) {
//                builder.append("push ").append(literal.value.intValue()).append("\n"); todo
            }
            else if (literal.type == Literal.FLOAT) {
//                builder.append("push [").append(ast.getConstantAddress(literal.value)).append("]").append("\n"); todo
            }
        } else if (operand instanceof Operator operator) {
            String operatorCommand = switch (operator.type) {
                case ProgramExecutor.ADD -> "add";
                case ProgramExecutor.SUB -> "sub";
                case ProgramExecutor.MUL -> "mul";
                case ProgramExecutor.DIV -> "div";


                default -> null;
            };
//            builder.append(operatorCommand).append(" [esp-2], [esp-1]").append("\n");
//            builder.append("pop").append("\n"); todo
        } else if (operand instanceof Logical logical) {
//            builder.append("; Logical expression\n"); todo
//            for (int i = 2; i < logical.operands.length; i += 2) {
//                int labelId = autogenerated_labelId++;
//
//                Operand left = logical.operands[i - 2];
//                compileExpression(left);
//                builder.append("pop eax\n");
//                builder.append("cmp eax, 0\n");
//
//                byte operator = ((Operator) logical.operands[i - 1]).type;
//                if (operator == Logical.OR) {
//                    builder.append("jne success").append(labelId).append("\n");
//                } else {
//                    builder.append("je fail").append(labelId).append("\n");
//                }
//                builder.append("\n");
//
//                Operand right = logical.operands[i];
//                compileExpression(right);
//
//                builder.append("pop eax\n");
//                builder.append("cmp eax, 0\n");
//                if (operator == Logical.OR) {
//                    builder.append("jne success").append(labelId).append("\n");
//                } else {
//                    builder.append("je fail").append(labelId).append("\n");
//                }
//                builder.append("\n");
//
//                if (operator == Logical.OR) {
//                    builder.append("push 0\n");
//                    builder.append("jmp after").append(labelId).append("\n");;
//                    builder.append("success").append(labelId).append(":\n");;
//                    builder.append("push 1\n\n");
//                    builder.append("after").append(labelId).append(":\n");;
//                } else {
//                    builder.append("push 1\n");
//                    builder.append("jmp after").append(labelId).append("\n");;
//                    builder.append("fail").append(labelId).append(":\n");;
//                    builder.append("push 0\n\n");
//                    builder.append("after").append(labelId).append(":\n");;
//                }
//            }
//        } else if (operand instanceof Arithmetic arithmetic) {
//            builder.append("; Arithmetic expression\n");
//            for (Operand operand1 : arithmetic.operands) {
//                compileExpression(operand1);
//            }
//            builder.append("\n");
//        } else if (operand instanceof Assign assign) {
//            builder.append("; Variable assign\n");
//            compileExpression(assign.value);
//
//            // Compiles indices and saves them on stack
//            for (int i = assign.indices.length - 1; i >= 0; i--) {
//                builder.append("; Index ").append(i).append("\n");
//                compileExpression(assign.indices[i]);
//            }
//
//            // Pops all indices from stack and calculates the offset
//            builder.append("mov eax, ").append(assign.variable.offset).append("\n");
//            for (int i = assign.indices.length - 1; i >= 0; i--) {
//                builder.append("; ").append(i).append(". operand\n");
//                builder.append("pop ebx\n");
//
//                if (i != 0)
//                    builder.append("mul ebx, ").append(assign.variable.lengths[i]).append("\n");
//
//                builder.append("add eax, ebx\n");
//            }
//
//            builder.append("mov [").append(assign.variable.global ? "eax" : ("ebp+" + "eax")).append("], [esp-1]\n");
//            builder.append("\n");
//        } else if (operand instanceof Access access) {
//            builder.append("; Variable access\n");
//
//            // Compiles indices and saves them on stack
//            for (int i = access.indices.length - 1; i >= 0; i--) {
//                builder.append("; Index ").append(i).append("\n");
//                compileExpression(access.indices[i]);
//            }
//
//            // Pops all indices from stack and calculates the offset
//            builder.append("mov eax, ").append(access.variable.offset).append("\n");
//            for (int i = access.indices.length - 1; i >= 0; i--) {
//                builder.append("; ").append(i).append(". operand\n");
//                builder.append("pop ebx\n");
//
//                if (i != 0)
//                    builder.append("mul ebx, ").append(access.variable.lengths[i]).append("\n");
//
//                builder.append("add eax, ebx\n");
//            }
//
//            builder.append("push [").append(access.variable.global ? "eax" : ("ebp+" + "eax")).append("]\n");
//        } else if (operand instanceof Call call) {
//            builder.append("; Function call\n");
//
//            for (Operand[] argument : call.arguments) {
//                for (Operand operand1 : argument) {
//                    compileExpression(operand1);
//                }
//            }
//
//            if (call.function.module != null) {
//                builder.append("push ").append(call.arguments.length).append("\n");
//            }
//
//            builder.append("call ").append(call.function.module != null ? ("." + ast.getFunctionOffset(call.function)) : call.function.name).append("\n");
//            if (call.function.module != null) {
//                builder.append("sub esp, ").append(1 + call.arguments.length).append("\n");
//            } else {
//                builder.append("sub esp, ").append(call.arguments.length).append("\n");
//            }
//            builder.append("push rax\n");
//        } else if (operand instanceof Compare compare) {
//            int labelId = autogenerated_labelId++;
//            compileExpression(compare.left);
//            compileExpression(compare.right);
//
//            builder.append("cmp [esp-2], [esp-1]\n");
//            builder.append("sub esp, 2\n");
//            switch (compare.operation) {
//                case Compare.EQUALS -> builder.append("jne fail").append(labelId).append("\n");
//                case Compare.NOT_EQUALS -> builder.append("je fail").append(labelId).append("\n");
//                case Compare.LESS_THAN -> builder.append("jge fail").append(labelId).append("\n");
//                case Compare.GREATER_THAN -> builder.append("jle fail").append(labelId).append("\n");
//                case Compare.LESS_EQUALS -> builder.append("jg fail").append(labelId).append("\n");
//                case Compare.GREATER_EQUALS -> builder.append("jl fail").append(labelId).append("\n");
//            };
//
//            builder.append("push 1\n");
//            builder.append("jmp after").append(labelId).append("\n");
//
//            builder.append("fail").append(labelId).append(":\n");
//            builder.append("push 0\n");
//
//            builder.append("after").append(labelId).append(":\n");
//            builder.append("\n");
//
//            // Both results are now in stack
//        }
//
//        else if (operand instanceof Unary unary) {
//            builder.append("; Unary\n");
//            // if prefix
//            if (unary.operation == Unary.PREFIX_INCREMENT || unary.operation == Unary.PREFIX_DECREMENT) {
//                compileExpression(new Assign(unary.operand.variable, unary.operand.indices, new Arithmetic(new Operand[]{
//                  unary.operand,
//                  new Literal(Literal.INT, unary.operation == Unary.PREFIX_INCREMENT ? 1 : -1),
//                  Operator.ADD
//                })));
//            }
//            else {
//                builder.append("; Push variable onto stack\n");
//                compileExpression(unary.operand); // pushes variable value onto the stack
//                builder.append("; Update variable\n");
//                compileExpression(new Assign(unary.operand.variable, unary.operand.indices, new Arithmetic(new Operand[]{
//                  unary.operand,
//                  new Literal(Literal.INT, unary.operation == Unary.POSTFIX_INCREMENT ? 1 : -1),
//                  Operator.ADD
//                })));
//                builder.append("pop\n");
//            }
//        }
//
//        else if (operand instanceof Cast cast) {
//            builder.append("; Cast\n");
//            compileExpression(cast.operand);
//            if (cast.operand.getResultType() == Primitive.FLOAT && cast.type == Primitive.INT) {
//                builder.append("cflti\n");
//            }
//            else if (cast.operand.getResultType() == Primitive.INT && cast.type == Primitive.FLOAT) {
//                builder.append("ciflt\n");
//            }
//            // todo: maybe throw an error, it shouldn't be anything else cause parser took care of it
//        }
//
//        else if (operand instanceof Concat concat) {
//            builder.append("; string concat\n");
//            compileExpression(concat.left);
//            compileExpression(concat.right);
//            builder.append("cat").append(" [esp-2], [esp-1]").append("\n");
//            builder.append("pop").append("\n");
//        } todo
        }
    }

    public void compileVariableDeclare(Declare declare) {
//        builder.append("; Variable declare\n"); todo
        int sum = declare.length;

        // generate array members
        if (declare.length != 1) {
            String toPush;
            if (declare.type == Primitive.INT)
                toPush = "0";
            else toPush = null;

            if (toPush != null) {
                for (int i = 0; i < declare.length; i++) {
//                    append("push " + toPush); todo
                }
            } else {
//                append("add esp, " + sum); todo
            }
        }
        else if (declare.value != null) {
            compileExpression(declare.value);
            // todo: don't i need to pop here?
        } else {
//            builder.append("add esp, ").append(sum).append("\n"); todo
        }
    }

    @Override
    public byte[] getOutput() {
        return builder.getBytes();
    }

}
